(DEFUN C:SBS-WP (/ SP EP WD LP HP PL RP PW PX PY PH OSM CMD BH PS BP CO *error* msg )
	(DEFUN *error* ( msg )
		(if CMD (setvar 'CMDECHO CMD))
		(if OSM (setvar 'OSMODE OSM))
		(if (not (member msg '("Function cancelled" "quit / exit abort")))
            (princ (strcat "\nError: " msg))
        )
        (princ)
    )
	;;Wall info Gathering
	(SETQ
		CMD (GETVAR "CMDECHO")
		OSM (GETVAR "OSMODE")
		SP (GETPOINT "\nSelect Wall Start Point:")
		EP (GETPOINT "\nSelect Wall End Point:")
		LP (GETPOINT "\nLow Eave hight:")
		HP (GETPOINT "\nHigh eave or peak")
	)
	(SBS-PANEL-DIA)
	(SETQ 
		PW (atoi(NTH 1 (assoc "WIDTH" ~PANEL~)))
		BH (distof (NTH 1 (assoc "BASE" ~PANEL~)) 4)
	)		
	;;Calculate Length or wall "x" and "y" of roof slope 
	(SETQ 
		WD (DISTANCE (LIST (CAR SP) 0.0 0.0) (LIST (CAR EP) 0.0 0.0))
		PH (DISTANCE (LIST 0.0 (CADR SP) 0.0) (LIST 0.0 (CADR HP) 0.0))
		PX (DISTANCE (LIST (CAR LP) 0.0 0.0) (LIST (CAR HP) 0.0 0.0))
		PY (DISTANCE (LIST 0.0 (CADR LP) 0.0) (LIST 0.0 (CADR HP) 0.0))
		PS (DISTANCE (LIST 0.0 (CADR SP) 0.0) (LIST 0.0 (CADR LP) 0.0))
	)
	;;Calculate Pitch
	(SETQ RP (*(/ PY PX) PW))
	(print (STRCAT "Pitch: " (VL-PRINC-TO-STRING (*(/ PY PX) 12)) "/12"))
	(print RP)
	;;Determine panel length
	(print "a")
	(print SP)
	(print EP)
	(print LP)
	(print HP)
	(print PW)
	(print BH)
	(cond 
		((= RP 0) (SETQ PL (1- (- PS BH))))
		((and (> (*(/ PY PX) 12) 1.1) (and (<(CAR SP) (1+(CAR HP))) (>(car SP)(1-(car HP))))) (SETQ PL (- PH BH)))
		((and (> (*(/ PY PX) 12) 1.1) (and (<(CAR SP) (1+(CAR LP))) (>(car SP)(1-(car LP))))) (SETQ PL (+ RP (- PS BH))))
		((and (<= (*(/ PY PX) 12) 1.1) (and (<(CAR SP) (1+(CAR HP))) (>(car SP)(1-(car HP))))) (SETQ PL (- (- PH BH) RP)))
		((and (<= (*(/ PY PX) 12) 1.1) (and (<(CAR SP) (1+(CAR LP))) (>(car SP)(1-(car LP))))) (SETQ PL (- PS BH)))
		(T (setq PL PS) (PRINT "Start point and High/Low point are not aligned in the X coordinate. Output may not be as expected"))
	)
	;;Set Start point
	(print "b")
	(IF (< (CAR EP) (CAR SP))
		(SETQ BP (LIST (- (CAR SP) PW) (+ (CADR SP) BH) (CADDR SP)))
		(SETQ BP (LIST (CAR SP) (+(CADR SP) BH) (CADDR SP)))	
	)	
	;; Panel wall creation Function  
	(SETQ CO 0)
	(vla-StartUndoMark 
		(vla-get-ActiveDocument 
			(vlax-get-acad-object)
		)
	)
	(SETVAR "CMDECHO" 0)
	(SETVAR "OSMODE" 16384)
	(WHILE (< CO WD )
		(IF (> PL (- PH BH))
			(SETQ PL (- PH BH))
		)
		(IF (AND 
				(< PL (- PS BH))
				(/= RP 0)
			)
			(SETQ PL (- PS BH))
		)
		(PRINT BP)
		(SBS-PANELINSERT BP PL )
		(COND
			((AND (< (- PX CO) PW) (> CO PX)) (SETQ PL (- PL RP)))
			((AND (< (- PX CO) PW) (<= CO PX) (> (*(/ PY PX) 12) 1.1)) (SETQ PL (- (- PH BH)(* (/ RP PW) (- PW(- PX CO))))))
			((AND (< (- PX CO) PW) (<= CO PX) (<= (*(/ PY PX) 12) 1.1)) (SETQ PL (- (- (- PH BH) RP)(* (/ RP PW) (- PW(- PX CO))))))
			((AND (>= (- PX CO) PW) (and (<(CAR SP) (1+(CAR HP))) (>(car SP)(1-(car HP))))) (SETQ PL (- PL RP)))
			((AND (>= (- PX CO) PW) (and (<(CAR SP) (1+(CAR LP))) (>(car SP)(1-(car LP))))) (SETQ PL (+ PL RP)))
		)
		(IF (> (CAR EP) (CAR SP))
			(SETQ BP (LIST (+ (CAR BP) PW) (CADR BP) (CADDR BP)))
			(SETQ BP (LIST (- (CAR BP) PW) (CADR BP) (CADDR BP)))
		)
		(SETQ CO (+ CO PW))
	)
	(vla-EndUndoMark 
		(vla-get-ActiveDocument 
			(vlax-get-acad-object)
		)
	)
	(SETVAR "CMDECHO" CMD)
	(SETVAR "OSMODE" OSM)
	(PRINC)
)
